### ISSUE TITLE
Add install dependencies script

### ISSUE THREAD

**Issue by snobu** [adafruit/Adafruit-Motor-HAT-Python-Library#5]
You should probably add
`apt-get install -y python-smbus`

which brings in as a bonus:

``` bash
The following extra packages will be installed:
  i2c-tools
```

and something like

``` bash
# Auto load i2c kernel modules
# This works for Pi2, I think the Pi1 only has i2c-dev? No idea.
 if ! grep -q "i2c-" /etc/modules; then
    echo "i2c-dev" >> /etc/modules
    echo "i2c-bcm2708" >> /etc/modules
fi
```

to your build script.

Here's why,

On a vanilla Pi2 running Raspbian

``` bash
root@jazzy ~ # cat /etc/debian_version
7.8
```

after installing the Motor HAT library with
`python setup.py install`

You get this:

``` bash
root@jazzy ~/nodedemo/Adafruit-Motor-HAT-Python-Library/examples # python DCTest.py
Traceback (most recent call last):
  File "DCTest.py", line 2, in <module>
    from Adafruit_MotorHAT import Adafruit_MotorHAT, Adafruit_DCMotor
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_MotorHAT-1.2.0-py2.7.egg/Adafruit_MotorHAT/__init__.py", line 1, in <module>
    from .Adafruit_MotorHAT import Adafruit_StepperMotor, Adafruit_DCMotor, Adafruit_MotorHAT
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_MotorHAT-1.2.0-py2.7.egg/Adafruit_MotorHAT/Adafruit_MotorHAT.py", line 3, in <module>
    from Adafruit_PWM_Servo_Driver import PWM
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_MotorHAT-1.2.0-py2.7.egg/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 5, in <module>
    from Adafruit_I2C import Adafruit_I2C
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_MotorHAT-1.2.0-py2.7.egg/Adafruit_MotorHAT/Adafruit_I2C.py", line 3, in <module>
    import smbus
ImportError: No module named smbus
```

`python-smbus` is not there by default. `i2c-tools` isn't there either and `i2c` kernel modules aren't loaded.

**Comment by tdicola** [comment]
Ah thanks for the tip, yeah I actually just switched the library over to use a different GPIO lib that doesn't depend on python-smbus anymore (so now it can be python 3 compatible).  I'll close this for now but thanks again for the suggestion!
