### ISSUE TITLE
Problem Erno2

### ISSUE THREAD

**Issue by aluneau** [adafruit/Adafruit-Motor-HAT-Python-Library#6]
Hi,
I've receive my new Motor Hat for my raspberry pi 
I've installed the library with: https://learn.adafruit.com/adafruit-dc-and-stepper-motor-hat-for-raspberry-pi/installing-software 

but when I try examples i got this error:
`pi@raspberrypi:~/Adafruit-Motor-HAT-Python-Library/examples $ sudo python DCTest.py 
Traceback (most recent call last):
  File "DCTest.py", line 2, in <module>
    from Adafruit_MotorHAT import Adafruit_MotorHAT, Adafruit_DCMotor
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/__init__.py", line 1, in <module>
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_MotorHAT.py", line 3, in <module>
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 11, in <module>
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 35, in PWM
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_I2C.py", line 43, in __init__
IOError: [Errno 2] No such file or directory
`
I don't know what it is...

Thanks by advance for your help!

**Comment by blausand** [comment]
We have the same problem. Could you resolve it? Then share your wisdom, please! Thanks.

**Comment by tdicola** [comment]
Be sure you've enabled I2C on the pi with raspi-config.  The no such file error means the Pi can't find the /dev/i2c... devices.  Check this out for more details: https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c
